### PR TITLE
Refactor/endpoints

### PR DESCRIPTION
**Pull request by DavidWein94**
Removed old test and added a parameterised test for the endpoints

Should solve https://github.com/deNBI/OpenStackTests/issues/7

### CODE REVIEW

**Comment by DavidWein94** [comment]
Now it is possible to run all test  if you dont provide any parameter:
It will return sys.exit(0) if all test were succesfull, but if one test fails it will return sys.exit(2) with the appropriate message  and wont test the following services anymore.

Also you can get an explanation with the --help parameter

e.g python3 endpoint_test --help
It will show how to use the test and list the avaiable services which you can test

Also removed the endpoints from the config

**Comment by DavidWein94** [comment]
Test instructions : 
- pip3 install git+https://github.com/deNBI/OpenStackTests@refactor/endpoints
- complete the  fields in the config.yml and the complex_test.yml
- run the test : python3 create_and_delete_image.py , python3 complex_test.py , python3 endpoint_test PARAM

**Comment by DavidWein94** [comment]
2) ssh-keys. It should ne possible to generate a fresh ssh-key, register/upload and use it
--> no need to configure ssh-keys in complex.yml any more (makes life easier)

Should be implemented now

**Comment by pbelmann** [comment]
@DavidWein94  Is this PR ready to test again or is this work in progress?

**Comment by DavidWein94** [comment]
Why need to configure XXX_name and XXX_id ?
--> 2nd Basic test ' create_and_delete_image.py' needs os_user_domain_id while os_user_domain_name is given.

Only uses names now...

Now everything should work,

**Comment by jkrue** [comment]
We tested the OpenStackTest against our dev setup. Everything works as expected ...

**Pull request merged**
